### ISSUE TITLE
Is this plugin for adding Mediawik authentication?

### ISSUE THREAD

**Issue by sunjam** [paviliondev/discourse-wikimedia-auth#1]
I do not see any explicit discussion of this plugin on meta or pavilion.  Thanks for any info!

**Comment by GokulNC** [comment]
Why not just try it out say at midnight or something?

**Comment by sunjam** [comment]
Sure, I'll try it out.  Any documentation at all is appreciated!

**Comment by angusmcleod** [comment]
Hey guys, yes this plugin lets you authenticate in Discourse using this [omniauth strategy](https://github.com/timwaters/omniauth-mediawiki). It was originally developed for Wikimedia for https://discuss-space.wmflabs.org.

I have various pieces of private documentation which I'll try to clean up and release sometime in the next week or so.

**Comment by sunjam** [comment]
Cool, it is working.  I'd like to use it with our mediawiki instance as opposed to Wikipedia.  Great piece of software!
