### ISSUE TITLE
Wikimedia-auth disables account creation via email

### ISSUE THREAD

**Issue by sunjam** [paviliondev/discourse-wikimedia-auth#2]
On latest Tests-Pass beta4 of Discourse Wikimedia-auth causes email account creation to be disabled entirely.  Obviously want users to be able to use this login method, but I'm unsure on how to keep it from disabling standard email account creation.

**Comment by angusmcleod** [comment]
Closed in favour of https://github.com/paviliondev/discourse-wikimedia-auth/issues/4
